version: "3.1"

secrets:
  aes_key:
    file: ./secrets/aes_key.txt

services:
  helix:
    build: ../helix
    container_name: helix-sandbox
    ports:
      - 5000:5000
    secrets:
      - aes_key
    volumes:
      - ../helix:/helix
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AES_KEY=/run/secrets/aes_key
      - FLASK_CONFIG=development
